"""Add BackgroundJob model for async processing

Revision ID: ba4c405e5f94
Revises: 7bf303298523
Create Date: 2025-11-19 12:58:38.822862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4c405e5f94'
down_revision: Union[str, Sequence[str], None] = '7bf303298523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_job_created_at'), 'background_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_job_status'), 'background_job', ['status'], unique=False)
    op.drop_index(op.f('idx_api_usage_org_time'), table_name='api_usage_log')
    op.drop_index(op.f('idx_org_member_org'), table_name='organization_member')
    op.drop_index(op.f('idx_org_member_user'), table_name='organization_member')
    op.drop_index(op.f('idx_quiz_organization'), table_name='quiz')
    op.drop_index(op.f('idx_quiz_standard'), table_name='quiz')
    op.drop_index(op.f('idx_quiz_user_created'), table_name='quiz')
    op.drop_index(op.f('idx_question_submission'), table_name='quiz_question')
    op.drop_index(op.f('idx_submission_quiz'), table_name='quiz_submission')
    op.drop_index(op.f('idx_submission_student'), table_name='quiz_submission')
    op.drop_index(op.f('idx_student_organization'), table_name='student')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_student_organization'), 'student', ['organization_id'], unique=False)
    op.create_index(op.f('idx_submission_student'), 'quiz_submission', ['student_id'], unique=False)
    op.create_index(op.f('idx_submission_quiz'), 'quiz_submission', ['quiz_id'], unique=False)
    op.create_index(op.f('idx_question_submission'), 'quiz_question', ['quiz_submission_id'], unique=False)
    op.create_index(op.f('idx_quiz_user_created'), 'quiz', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_quiz_standard'), 'quiz', ['standard_id'], unique=False)
    op.create_index(op.f('idx_quiz_organization'), 'quiz', ['organization_id'], unique=False)
    op.create_index(op.f('idx_org_member_user'), 'organization_member', ['user_id'], unique=False)
    op.create_index(op.f('idx_org_member_org'), 'organization_member', ['organization_id'], unique=False)
    op.create_index(op.f('idx_api_usage_org_time'), 'api_usage_log', ['organization_id', sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_background_job_status'), table_name='background_job')
    op.drop_index(op.f('ix_background_job_created_at'), table_name='background_job')
    op.drop_table('background_job')
    # ### end Alembic commands ###
